{{- $appName := printf "%s-custom-hpa" .Values.target.deployment -}}
{{- if .Values.appNameSuffix }}
  {{- $appName = print $appName "-" .Values.appNameSuffix }}
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
      labels:
        app: {{ $appName }}
    spec:
      containers:
        - name: {{ $appName }}
          image: "nanit/kubernetes-custom-hpa:{{ tpl .Values.imageTag . }}"
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            - name: PORT
              value: "3000"
            - name: CONTROL_LOOP_PERIOD
              value: "{{ .Values.controlLoopPeriod }}"
            - name: DEPLOYMENT
              value: "{{ .Values.target.deployment }}"
            - name: NAMESPACE
              value: "{{ .Values.target.namespace }}"
            - name: TARGET_VALUE
              value: "{{ .Values.target.value }}"
            - name: MIN_REPLICAS
              value: "{{ .Values.minReplicas }}"
            - name: MAX_REPLICAS
              value: "{{ .Values.maxReplicas }}"
            - name: SCALE_UP_COOLDOWN
              value: "{{ .Values.behavior.scaleUpCooldown }}"
            - name: SCALE_DOWN_COOLDOWN
              value: "{{ .Values.behavior.scaleDownCooldown }}"
            - name: SCALE_UP_MIN_FACTOR
              value: "{{ .Values.behavior.scaleUpMinFactor }}"
            - name: SCALE_UP_MAX_FACTOR
              value: "{{ .Values.behavior.scaleUpMaxFactor }}"
            - name: SCALE_DOWN_MIN_FACTOR
              value: "{{ .Values.behavior.scaleDownMinFactor }}"
            - name: SCALE_DOWN_MAX_FACTOR
              value: "{{ .Values.behavior.scaleDownMaxFactor }}"
            - name: DRY_RUN
              value: "{{ .Values.dryRun }}"
            - name: PROMETHEUS_URL
              value: "{{ .Values.prometheus.url }}"
            - name: PROMETHEUS_PORT
              value: "{{ .Values.prometheus.port }}"
            - name: PROMETHEUS_QUERY
              value: {{ .Values.prometheus.query }}
            - name: JAVA_OPTS
              value: "-Djdk.tls.client.protocols=TLSv1.2"
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}